export const ADD_ITEM_ACTION = 'ADD_ITEM_ACTION';
export const REMOVE_ITEM_ACTION = 'REMOVE_ITEM_ACTION';
export const CHANGE_MODE_ACTION = 'CHANGE_MODE_ACTION';
export const SEARCH_ACTION = 'SEARCH_ACTION';
